### ISSUE TITLE
this repo appears necessary so that we have docs.neurodata.io --> all our gh-pages

### ISSUE THREAD

**Issue by alexbaden** [neurodata/neurodata.github.io#3]
@j6k4m8 @willgray @jovo 

Seems like we should change the readme for when we all get hit by a bus?

**Comment by jovo** [comment]
agreed!

On Fri, Feb 5, 2016 at 5:44 PM, Alex Baden notifications@github.com wrote:

> @j6k4m8 https://github.com/j6k4m8 @willgray
> https://github.com/willgray @jovo https://github.com/jovo
> 
> Seems like we should change the readme for when we all get hit by a bus?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/neurodata.github.io/issues/3.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
@alexbaden @perlman is this still true?

**Comment by alexbaden** [comment]
Yes. The `index.html` page in this repo forwards the user to `docs.neurodata.io/nddocs` which is where the docs live. This repo lives at `docs.neurodata.io` and gives us the `docs.neurodata.io` CNAME on github.

**Comment by alexbaden** [comment]
I updated the README file, so I think we can close this.
