### ISSUE TITLE
Bumbarger spelled wrong

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.github.io#5]
- [x] the title is "Bombarger", but the "o" should be a "u"
- [x] also, no link to viz, but we have catmaid viz, so let's either ingest or link to catmaid.

**Comment by alexbaden** [comment]
Stealing. 🗡

**Comment by alexbaden** [comment]
Linked to catmaid. Ingesting all current catmaid-only projects seems to be a good discussion topic for move-to-the-cloud meetings. There are a few of them written down somewhere in github...

**Comment by jovo** [comment]
https://github.com/neurodata/internal/issues/49

agreed. @perlman @kunallillaney @gkiar

**Comment by gkiar** [comment]
Thanks for stealing, @alexbaden ! :fire:
